services:

  database:
    container_name: url_shortener_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - url_shortener_postgres_data:/var/lib/postgresql/data

volumes:
  url_shortener_postgres_data: