services:

  cassandra-node1:
    image: cassandra:4.1
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME}
      CASSANDRA_ENDPOINT_SNITCH: ${CASSANDRA_SNTCH}
      CASSANDRA_DC: ${CASSANDRA_DC}
    volumes:
      - cassandra_data1:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES'"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    environment:
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME}
      CASSANDRA_ENDPOINT_SNITCH: ${CASSANDRA_SNTCH}
      CASSANDRA_DC: ${CASSANDRA_DC}
      CASSANDRA_SEEDS: ${CASSANDRA_SEEDS}
    depends_on:
      - cassandra-node1
    volumes:
      - cassandra_data2:/var/lib/cassandra

  writer-service:
    build:
      context: .
      dockerfile: Dockerfile.writer
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      cassandra-node1:
        condition: service_healthy

  reader-service:
    build:
      context: .
      dockerfile: Dockerfile.reader
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      cassandra-node1:
        condition: service_healthy


volumes:
  cassandra_data1:
  cassandra_data2: